### ISSUE TITLE
Destination folder

### ISSUE THREAD

**Issue by Jimbo623** [edjroot/webext-save-to-folder#1]
When I save the path to the download folder the backslash turns into a forward slash.So it won't work.  jimboehlers@kc.rr.com  Thanks

**Comment by Classy-Cube** [comment]
I believe it’s intentional since it would be easy to notice also using forward slashes may not conflict. I know windows file explorer uses forward slashes ( / ) but often allows using backslashes instead. I’m not sure if this is a case where it only works with forward slashes however.
Inside options.js is code where upon clicking save changes backslashes to forward slashes.
```
function onSave() {
  const $folder = $(this).closest('.folder’);
  const $path = $folder.find('.path’);
  let path = $path.val().trim()
    .replace(/\\+/g, '/')  // Windows-style > UNIX-style slashes
    .split('/').reduce((p,c)=>{return p.trim()+’/’+c.trim()}) // Remove spaces next to slashes
    .replace(/\/\/+/g, ‘/’)  // Remove duplicate slashes
    .replace(/^\/|\/$/g, ‘’);  // Remove first and last slashes
```
You may have the issue I had which was having the full path in the folder list options, instead have what comes after your default downloads folder. 
So, instead of entering “C:\Users\Username\Downloads\dl-redirect\pictures”, you must type just “dl-redirect\pictures”.

**Comment by edjroot** [comment]
Oh, wow, I'm really sorry! I must have missed this issue from the notifications.

Classy-Cube is right, this is intentional. The current behavior may not be the most elegant thing in the world, but I don't think it's what has caused your problem (once again, I'd say Classy is right). (Thanks, Cube! Very classy of you.)

Apparently this is a common source of confusion, since several people have complained about having to set relative paths. If you can think up some seamless way of auto-adjusting the paths, or at least guiding users to doing what they're supposed to do (preferably nicer than a red popup saying "rtfm ur doofus"), I'd greatly appreciate it :)

**Comment by edjroot** [comment]
Closing this as I think the issue lies somewhere else, but feel free to complain if I'm wrong.

**Comment by Classy-Cube** [comment]
So full paths do not work and relative paths are needed? 
I believe writing that beneath the Folder lists header would be a good idea.
As of now, the two ways a user would know are below.
![save-to-folder](https://user-images.githubusercontent.com/13388890/37065885-de297f2a-2170-11e8-9a7e-d9067a80c5ff.png)
When I read “Path (default:Downloads/)” I figured this was a shortened to fit in the field or at least not required. As for the Help/about I missed it before posting my issue. I’ve not seen a helpful FAQ included in extensions so didn’t think to search the options.

**Comment by edjroot** [comment]
> So full paths do not work and relative paths are needed?

Exactly (and unfortunately there's nothing I can do about it since it's enforced by Chrome). Looking back at how I wrote it, I don't think I would've understood it myself. I'll probably follow your suggestion and also reword the "TL;DR" as soon as I get some free time. Thanks again!
